### ISSUE TITLE
cyではじまるストロークが重複定義されている

### ISSUE THREAD

**Issue by papinianus** [shinespark/dvorakjp-romantable#18]
cyが、先頭のほうでky(きゃ行)の互換ストロークとして、また後にty(ちゃ行)の互換ストロークとして、重複定義されている。

どちらにするかは、ユーザの感覚によるところも大きいが、個人的にはky代替が適当に思う

**Comment by shinespark** [comment]
@papinianus 

Issueありがとうございます。

検討してみたのですが下記理由より、`ちゃ行` 相当で定義を統一することにします。

* Google 日本語入力では `ch*`, `cy*` ともに`ちゃ行`として扱っている
* [DvorakJP - 日本語入力用拡張Dvorak](http://www7.plala.or.jp/dvorakjp/dvorakjp.htm) でも以下のように促音は
  * > 「きゃ」行は「CN」で入力します、例えば「きゃ」の場合は「cna」に成ります。
  * > また「cha」は元のまま「ちゃ」と成ります。

他ローマ字テーブルからの移行コストの低減の観点なども鑑みて、訓令式ローマ字やGoogle 日本語入力の定義を踏襲している `ちゃ行` にするのが適当かと判断しました。

あくまで私個人の判断ですので、forkして`きゃ行`に変更して利用していただいても結構かと思います。
ありがとうございました。
